/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.UsuarioController;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.GridLayout;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JPopupMenu;
import javax.swing.JTextField;
import utilidades.GeneradorDeHash;
import utilidades.SesionUsuario;

/**
 *
 * @author felip
 */
public class Dashboard extends javax.swing.JFrame {
    
    private UsuarioController controller = new UsuarioController();

    
    public Dashboard() {
        initComponents();
        initContent();
        setDate();               
        setResizable(false);   
        setTitle("InterManager");        
        
    }
    
    private void setDate() {
        LocalDate now = LocalDate.now();
        Locale spanishLocale = new Locale("es", "ES");
        lblFecha.setText(now.format(DateTimeFormatter.ofPattern("EEEE dd 'de' MMMM 'de' yyyy", spanishLocale)));        
    }
        
    
    private void initContent(){
        
        ShowJPanel(new MenuPrincipal());
    }
    
    public static void ShowJPanel(JPanel p) {
        
        p.setSize(780, 480);
        p.setLocation(0,0);
        
        panelDisplay.removeAll();
        panelDisplay.add(p, BorderLayout.CENTER);
        panelDisplay.revalidate();
        panelDisplay.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        panelMenuLateral = new javax.swing.JPanel();
        lblInterManager = new javax.swing.JLabel();
        btnInicio = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnClientes = new javax.swing.JButton();
        btnTransacciones = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        lblConfiguracion = new javax.swing.JLabel();
        panelHeader = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblIconoIntermediario = new javax.swing.JLabel();
        panelDisplay = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(245, 245, 245));
        panelBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenuLateral.setBackground(new java.awt.Color(7, 71, 161));
        panelMenuLateral.setToolTipText("");
        panelMenuLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblInterManager.setFont(new java.awt.Font("Eras Demi ITC", 0, 32)); // NOI18N
        lblInterManager.setForeground(new java.awt.Color(245, 245, 245));
        lblInterManager.setText("InterManager");
        panelMenuLateral.add(lblInterManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, -1));

        btnInicio.setBackground(new java.awt.Color(15, 91, 178));
        btnInicio.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(245, 245, 245));
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hogar.png"))); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 12, 1, 1, new java.awt.Color(0, 0, 0)));
        btnInicio.setBorderPainted(false);
        btnInicio.setFocusable(false);
        btnInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInicioMouseEntered(evt);
            }
        });
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        panelMenuLateral.add(btnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 128, 243, 50));

        btnProductos.setBackground(new java.awt.Color(15, 91, 178));
        btnProductos.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(245, 245, 245));
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/producto.png"))); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 12, 1, 1, new java.awt.Color(0, 0, 0)));
        btnProductos.setBorderPainted(false);
        btnProductos.setFocusable(false);
        btnProductos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProductosMouseEntered(evt);
            }
        });
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        panelMenuLateral.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 243, 50));

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        panelMenuLateral.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, 10));

        btnClientes.setBackground(new java.awt.Color(15, 91, 178));
        btnClientes.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(245, 245, 245));
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/personas.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 12, 1, 1, new java.awt.Color(0, 0, 0)));
        btnClientes.setBorderPainted(false);
        btnClientes.setFocusable(false);
        btnClientes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClientesMouseEntered(evt);
            }
        });
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        panelMenuLateral.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 284, 243, 50));

        btnTransacciones.setBackground(new java.awt.Color(15, 91, 178));
        btnTransacciones.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnTransacciones.setForeground(new java.awt.Color(245, 245, 245));
        btnTransacciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transaccion (1).png"))); // NOI18N
        btnTransacciones.setText("Transacciones");
        btnTransacciones.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 12, 1, 1, new java.awt.Color(0, 0, 0)));
        btnTransacciones.setBorderPainted(false);
        btnTransacciones.setFocusable(false);
        btnTransacciones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTransacciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTransaccionesMouseEntered(evt);
            }
        });
        btnTransacciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaccionesActionPerformed(evt);
            }
        });
        panelMenuLateral.add(btnTransacciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 336, 243, 50));

        btnReportes.setBackground(new java.awt.Color(15, 91, 178));
        btnReportes.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(245, 245, 245));
        btnReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reporte-de-negocios.png"))); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 12, 1, 1, new java.awt.Color(0, 0, 0)));
        btnReportes.setBorderPainted(false);
        btnReportes.setFocusable(false);
        btnReportes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReportesMouseEntered(evt);
            }
        });
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        panelMenuLateral.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 388, 243, 50));

        btnProveedores.setBackground(new java.awt.Color(15, 91, 178));
        btnProveedores.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnProveedores.setForeground(new java.awt.Color(245, 245, 245));
        btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proveedor (2).png"))); // NOI18N
        btnProveedores.setText("Proveedores");
        btnProveedores.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 12, 1, 1, new java.awt.Color(0, 0, 0)));
        btnProveedores.setBorderPainted(false);
        btnProveedores.setFocusable(false);
        btnProveedores.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProveedoresMouseEntered(evt);
            }
        });
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        panelMenuLateral.add(btnProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 232, 243, 50));

        lblConfiguracion.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblConfiguracion.setForeground(new java.awt.Color(245, 245, 245));
        lblConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/configuraciones (3).png"))); // NOI18N
        lblConfiguracion.setText("Configuración");
        lblConfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConfiguracionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblConfiguracionMouseEntered(evt);
            }
        });
        panelMenuLateral.add(lblConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, 32));

        panelBackground.add(panelMenuLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 610));

        panelHeader.setBackground(new java.awt.Color(0, 103, 205));
        panelHeader.setPreferredSize(new java.awt.Dimension(744, 150));

        lblTitulo.setFont(new java.awt.Font("Dialog", 0, 21)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(245, 245, 245));
        lblTitulo.setText("Administración para Intermediarios");

        lblFecha.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(245, 245, 245));
        lblFecha.setText("Fecha");

        lblIconoIntermediario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/intermediario (1).png"))); // NOI18N

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo))
                .addGap(273, 273, 273)
                .addComponent(lblIconoIntermediario)
                .addGap(30, 30, 30))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIconoIntermediario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFecha)))
                .addGap(12, 12, 12))
        );

        panelBackground.add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 780, 128));

        panelDisplay.setBackground(new java.awt.Color(245, 245, 245));

        javax.swing.GroupLayout panelDisplayLayout = new javax.swing.GroupLayout(panelDisplay);
        panelDisplay.setLayout(panelDisplayLayout);
        panelDisplayLayout.setHorizontalGroup(
            panelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        panelDisplayLayout.setVerticalGroup(
            panelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        panelBackground.add(panelDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 770, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new MenuPrincipal());
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new ProductoPanel());
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new ClientePanel());
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnTransaccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaccionesActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new TransaccionPanel());
        
    }//GEN-LAST:event_btnTransaccionesActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new ReportePanel());        
        
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseEntered
        // TODO add your handling code here:       
        btnInicio.setCursor(new Cursor(Cursor.HAND_CURSOR));    
        
    }//GEN-LAST:event_btnInicioMouseEntered

    private void btnProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductosMouseEntered
        // TODO add your handling code here:        
        btnProductos.setCursor(new Cursor(Cursor.HAND_CURSOR));        
    }//GEN-LAST:event_btnProductosMouseEntered

    private void btnClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseEntered
        // TODO add your handling code here:
        btnClientes.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnClientesMouseEntered

    private void btnTransaccionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaccionesMouseEntered
        // TODO add your handling code here:
        btnTransacciones.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnTransaccionesMouseEntered

    private void btnReportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportesMouseEntered
        // TODO add your handling code here:
        btnReportes.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnReportesMouseEntered

    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked
        // TODO add your handling code here:                       
    }//GEN-LAST:event_btnInicioMouseClicked

    private void btnProveedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedoresMouseEntered
        // TODO add your handling code here:
        btnProveedores.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnProveedoresMouseEntered

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        // TODO add your handling code here:
        ShowJPanel(new ProveedorPanel());
        
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void lblConfiguracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfiguracionMouseClicked
        // TODO add your handling code here:
        JPopupMenu menuConfiguracion = new JPopupMenu();

        JMenuItem itemCerrarSesion = new JMenuItem("Cerrar sesión");
        JMenuItem itemModificarDatos = new JMenuItem("Modificar datos personales");
        //JMenuItem itemCerrarSesion = new JMenuItem("Cerrar sesión");
        JMenuItem itemEliminarCuenta = new JMenuItem("Eliminar cuenta");

        menuConfiguracion.add(itemCerrarSesion);
        menuConfiguracion.add(itemModificarDatos);
        menuConfiguracion.add(itemEliminarCuenta);
        menuConfiguracion.show(lblConfiguracion, lblConfiguracion.getWidth(), lblConfiguracion.getHeight());
        
        itemModificarDatos.addActionListener(e -> {
        
            // Formulario para que el Usuario pueda modificar sus datos
        System.out.println("Modificar datos personales");
        JPanel panel = new JPanel(new GridLayout(4, 2, 10, 10));
            JTextField txtNombre = new JTextField(SesionUsuario.getUsuario().getNombre());
            JTextField txtEmail = new JTextField(SesionUsuario.getUsuario().getEmail());
            JPasswordField txtClaveActual = new JPasswordField();
            JPasswordField txtClave = new JPasswordField();            

            panel.add(new JLabel("Nombre:"));
            panel.add(txtNombre);
            panel.add(new JLabel("Email:"));
            panel.add(txtEmail);
            panel.add(new JLabel("Contraseña actual:"));
            panel.add(txtClaveActual);
            panel.add(new JLabel("Nueva contraseña:"));
            panel.add(txtClave);            

            int result = JOptionPane.showConfirmDialog(null, panel, "Modificar datos personales",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            if (result == JOptionPane.OK_OPTION) {
                
                String nuevoNombre = txtNombre.getText();
                String nuevoEmail = txtEmail.getText();
                String claveActual = new String(txtClaveActual.getPassword());
                String nuevaClave = new String(txtClave.getPassword());

                // Actualizamos el nombre y email
                SesionUsuario.getUsuario().setNombre(nuevoNombre);
                SesionUsuario.getUsuario().setEmail(nuevoEmail);

                // Si hay nueva contraseña, verificamos que la actual se haya introducido correctamente para aplicar el cambio
                if (!nuevaClave.isEmpty()) {                

                  if (GeneradorDeHash.encriptarTexto(claveActual).equalsIgnoreCase(SesionUsuario.getUsuario().getContraseña())) {
                     
                      controller.actualizar(SesionUsuario.getUsuario().getId(), nuevoNombre, nuevoEmail, nuevaClave);
                     JOptionPane.showMessageDialog(null, "Datos y contraseña actualizados correctamente.");
                     
                    }   else {
                        JOptionPane.showMessageDialog(null, "La contraseña actual no es correcta.");
                        
                    }
                } else {
                        controller.actualizar(SesionUsuario.getUsuario().getId(), nuevoNombre, nuevoEmail, SesionUsuario.getUsuario().getContraseña());
                        JOptionPane.showMessageDialog(null, "Datos actualizados correctamente.");
                    }
                
            }
});

         itemCerrarSesion.addActionListener(e -> {
         
             //Mensaje para que el Usuario confirme la accion de cerrar sesión. Si es afirmativo, cerramos la sesion y volvemos a la pantalla de login
         int opcion = JOptionPane.showConfirmDialog(null, "¿Seguro que quieres cerrar sesión?", "Confirmar", JOptionPane.YES_NO_OPTION);
         if (opcion == JOptionPane.YES_OPTION) {
         SesionUsuario.cerrarSesion();
         this.dispose(); 

            LoginFrame login = new LoginFrame();
            login.setVisible(true);
            login.setLocationRelativeTo(null); 
         System.out.println("Cerrando sesión...");
    }
});
         
         itemEliminarCuenta.addActionListener(e -> {
             int opcion = JOptionPane.showConfirmDialog(null, "¿Seguro que quieres eliminar tu cuenta?", "Confirmar", JOptionPane.YES_NO_OPTION);
         if (opcion == JOptionPane.YES_OPTION) {
         //SesionUsuario.cerrarSesion();
         this.dispose(); 

            LoginFrame login = new LoginFrame();
            login.setVisible(true);
            login.setLocationRelativeTo(null); 
            
            controller.eliminar(SesionUsuario.getUsuario().getId());
            SesionUsuario.cerrarSesion();
             
         }
         });
    }//GEN-LAST:event_lblConfiguracionMouseClicked

    private void lblConfiguracionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConfiguracionMouseEntered
        // TODO add your handling code here:
        lblConfiguracion.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblConfiguracionMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnTransacciones;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblConfiguracion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIconoIntermediario;
    private javax.swing.JLabel lblInterManager;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelBackground;
    private static javax.swing.JPanel panelDisplay;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelMenuLateral;
    // End of variables declaration//GEN-END:variables
}
