/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.ProductoController;
import controlador.ProveedorController;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.GridLayout;
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import modelo.Producto;
import modelo.Proveedor;
import utilidades.ExportarCSV;
import utilidades.SesionUsuario;

/**
 *
 * @author felip
 */
public class ProveedorPanel extends javax.swing.JPanel {

    private ProveedorController controller = new ProveedorController();
    
    public ProveedorPanel() {
        initComponents();
        cargarProveedores("");
        tableProveedoresSetStyle();
        ordenarTabla();
    }
    
    private void tableProveedoresSetStyle(){
    JTableHeader header = tableProveedores.getTableHeader();
    header.setBackground(new Color(0,103,205)); 
    header.setForeground(Color.WHITE); 
    //header.setFont(new Font("Segoe UI", Font.BOLD, 14)); 
    lblLoSabias.setToolTipText("Haciendo clic en el encabezado de una columna puedes ordenar los datos.");
    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
    centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
    tableProveedores.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
    
    }
    private void cargarProveedores(String filtro) {
    DefaultTableModel model = (DefaultTableModel) tableProveedores.getModel();
    model.setRowCount(0);
    List<Proveedor> lista = controller.listarPorUsuario(SesionUsuario.getUsuario().getId());
    lista.stream()
        .filter(p -> p.isActivo() && (filtro.isEmpty() || p.getNombre().toLowerCase().contains(filtro.toLowerCase())))
        .forEach(p -> model.addRow(new Object[]{
            p.getId(),
            p.getNombre(),
            p.getEmail(),
            p.getTelefono()
        }));
    
}
    
    public void ordenarTabla(){
    TableRowSorter<TableModel> sorter = new TableRowSorter<>(tableProveedores.getModel());
    tableProveedores.setRowSorter(sorter);   
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userSearch = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProveedores = new javax.swing.JTable();
        txtfieldBuscador = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblTitulo1 = new javax.swing.JLabel();
        lblLoSabias = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(770, 480));

        lblTitulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTitulo.setText("Gestión de Proveedores");

        tableProveedores.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tableProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Email", "Teléfono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableProveedores.getTableHeader().setReorderingAllowed(false);
        tableProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tableProveedoresMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableProveedoresMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableProveedores);

        btnBuscar.setBackground(new java.awt.Color(18, 90, 173));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorderPainted(false);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuscar.setFocusable(false);
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
        });
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnNuevo.setBackground(new java.awt.Color(18, 90, 173));
        btnNuevo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorderPainted(false);
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevo.setFocusable(false);
        btnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevoMouseEntered(evt);
            }
        });
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(18, 90, 173));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.setBorderPainted(false);
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditar.setFocusable(false);
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarMouseEntered(evt);
            }
        });
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(18, 90, 173));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Borrar");
        btnEliminar.setBorderPainted(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminar.setFocusable(false);
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblTitulo1.setForeground(new java.awt.Color(126, 126, 126));
        lblTitulo1.setText("Filtrar por Nombre");

        lblLoSabias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lampara.png"))); // NOI18N
        lblLoSabias.setText("¿Lo sabías? ");
        lblLoSabias.setIconTextGap(0);

        btnImprimir.setBackground(new java.awt.Color(18, 90, 173));
        btnImprimir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnImprimir.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimir.setText("Exportar a CSV");
        btnImprimir.setActionCommand("");
        btnImprimir.setBorderPainted(false);
        btnImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnImprimir.setFocusable(false);
        btnImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnImprimirMouseEntered(evt);
            }
        });
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblLoSabias)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtfieldBuscador)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE))
                    .addComponent(lblTitulo1))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTitulo)
                .addGap(3, 3, 3)
                .addComponent(lblTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfieldBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminar)
                            .addComponent(btnEditar)
                            .addComponent(btnNuevo)
                            .addComponent(btnImprimir)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblLoSabias)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableProveedoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProveedoresMousePressed

    }//GEN-LAST:event_tableProveedoresMousePressed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        cargarProveedores(txtfieldBuscador.getText().trim());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        String nombre = JOptionPane.showInputDialog(this, "Nombre del proveedor:");
        String email = JOptionPane.showInputDialog(this, "Email del proveedor:");
        String telefono = JOptionPane.showInputDialog(this, "Teléfono del proveedor:");
        
    if (nombre != null && email != null && telefono != null &&
        !nombre.trim().isEmpty() && !email.trim().isEmpty() && !telefono.trim().isEmpty()) {
        
        boolean exito = controller.crear(nombre.trim(), email.trim(), telefono.trim(), SesionUsuario.getUsuario().getId());
        if (exito) {
            cargarProveedores("");
            
        } else {
            JOptionPane.showMessageDialog(this, "Error al crear el proveedor.");
        }
        
    } else {
        JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
    }
    }//GEN-LAST:event_btnNuevoActionPerformed
   
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int fila = tableProveedores.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona un proveedor para editar.");
        return;
    }

    int id = (int) tableProveedores.getValueAt(fila, 0);
    String nombreActual = (String) tableProveedores.getValueAt(fila, 1);
    String emailActual = (String) tableProveedores.getValueAt(fila, 2);
    String telefonoActual = (String) tableProveedores.getValueAt(fila, 3);

    JPanel panel = new JPanel(new GridLayout(3, 2, 10, 10));
            JTextField txtNombre = new JTextField(nombreActual);
            JTextField txtEmail = new JTextField(emailActual);
            JTextField txtTelefono = new JTextField(telefonoActual);         
            panel.add(new JLabel("Nombre:"));
            panel.add(txtNombre);
            panel.add(new JLabel("Email:"));
            panel.add(txtEmail);
            panel.add(new JLabel("Teléfono:"));
            panel.add(txtTelefono);                       
    
            int result = JOptionPane.showConfirmDialog(null, panel, "Modificar datos personales",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            if (result == JOptionPane.OK_OPTION) {
                
                String nuevoNombre = txtNombre.getText();
                String nuevoEmail = txtEmail.getText();
                String nuevoTelefono = txtTelefono.getText();  

    if (nuevoNombre != null && nuevoEmail != null && nuevoTelefono != null &&
        !nuevoNombre.trim().isEmpty() && !nuevoEmail.trim().isEmpty() && !nuevoTelefono.trim().isEmpty()) {

        boolean exito = controller.actualizar(id, nuevoNombre.trim(), nuevoEmail.trim(), nuevoTelefono.trim(), true, SesionUsuario.getUsuario().getId());
        if (exito) {
            cargarProveedores("");
        } else {
            JOptionPane.showMessageDialog(this, "Error al editar el proveedor.");
        }
        
    } else {
        JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
   }}
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila = tableProveedores.getSelectedRow();
        if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona un proveedor para eliminar.");
        return;
        }

        int id = (int) tableProveedores.getValueAt(fila, 0);
        int confirm = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas eliminar este proveedor?");
        
        if (confirm == JOptionPane.YES_OPTION) {
            boolean exito = controller.marcarComoInactivo(id, SesionUsuario.getUsuario().getId());
            if (exito) {
                cargarProveedores("");
        } else {
            JOptionPane.showMessageDialog(this, "No se puede eliminar el proveedor.");
        }
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tableProveedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProveedoresMouseEntered
        // TODO add your handling code here:
        JTableHeader header = tableProveedores.getTableHeader();
        
        int col = header.columnAtPoint(evt.getPoint());
        if (col != -1) {            
            header.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        } else {            
            header.setCursor(Cursor.getDefaultCursor());
        }               
    }//GEN-LAST:event_tableProveedoresMouseEntered

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        // TODO add your handling code here:
        btnBuscar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnNuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseEntered
        // TODO add your handling code here:
        btnNuevo.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnNuevoMouseEntered

    private void btnEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseEntered
        // TODO add your handling code here:
        btnEditar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnEditarMouseEntered

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        // TODO add your handling code here:
        btnEliminar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnImprimirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimirMouseEntered
        // TODO add your handling code here:
        btnImprimir.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnImprimirMouseEntered

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar como");
        fileChooser.setSelectedFile(new File("proveedores.csv"));

        int userSelection = fileChooser.showSaveDialog(this);        
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            ExportarCSV.exportarTablaCSV(tableProveedores, archivo);
        }
    }//GEN-LAST:event_btnImprimirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLoSabias;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JTable tableProveedores;
    private javax.swing.JTextField txtfieldBuscador;
    private javax.swing.JTextField userSearch;
    // End of variables declaration//GEN-END:variables
}
