/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.UsuarioController;
import java.awt.Cursor;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import modelo.Usuario;
import modelo.UsuarioDAO;
import utilidades.Validador;

/**
 *
 * @author felip
 */
public class RegistroFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public RegistroFrame() {
        initComponents();
        usuarioController = new UsuarioController();
        UsuarioDAO usuarioDao = new UsuarioDAO();
        setTitle("InterManager");
        txtNombre.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 10));           
        txtEmail.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 10));
        txtContrasenia.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 10));        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        Background = new javax.swing.JPanel();
        Encabezado = new javax.swing.JPanel();
        InterManager = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblIniciaSesion = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnRegistrarse = new javax.swing.JButton();
        txtCrearNuevaCuenta = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblContrasenia = new javax.swing.JLabel();
        txtContrasenia = new javax.swing.JPasswordField();
        txtEmail = new javax.swing.JTextField();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(27, 113, 212));

        Encabezado.setBackground(new java.awt.Color(28, 69, 157));

        InterManager.setFont(new java.awt.Font("Eras Demi ITC", 0, 24)); // NOI18N
        InterManager.setForeground(new java.awt.Color(245, 245, 245));
        InterManager.setText("InterManager");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout EncabezadoLayout = new javax.swing.GroupLayout(Encabezado);
        Encabezado.setLayout(EncabezadoLayout);
        EncabezadoLayout.setHorizontalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(InterManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EncabezadoLayout.setVerticalGroup(
            EncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncabezadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InterManager)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblIniciaSesion.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        lblIniciaSesion.setForeground(new java.awt.Color(245, 245, 245));
        lblIniciaSesion.setText("¿Ya tienes Cuenta? Inicia Sesión");
        lblIniciaSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIniciaSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblIniciaSesionMouseEntered(evt);
            }
        });

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 69, 157)));

        btnRegistrarse.setBackground(new java.awt.Color(130, 192, 255));
        btnRegistrarse.setFont(new java.awt.Font("Dialog", 0, 22)); // NOI18N
        btnRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarseMouseEntered(evt);
            }
        });
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });

        txtCrearNuevaCuenta.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        txtCrearNuevaCuenta.setForeground(new java.awt.Color(245, 245, 245));
        txtCrearNuevaCuenta.setText("Crear nueva cuenta");

        lblNombre.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(245, 245, 245));
        lblNombre.setText("Nombre");

        lblEmail.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(245, 245, 245));
        lblEmail.setText("Email");

        lblContrasenia.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblContrasenia.setForeground(new java.awt.Color(245, 245, 245));
        lblContrasenia.setText("Contraseña");

        txtContrasenia.setBackground(new java.awt.Color(255, 255, 255));
        txtContrasenia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 69, 157)));

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(28, 69, 157)));

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Encabezado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail)
                    .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                        .addComponent(btnRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblContrasenia)
                        .addComponent(txtContrasenia)
                        .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                        .addComponent(lblIniciaSesion))
                    .addComponent(lblNombre))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(txtCrearNuevaCuenta)
                .addGap(71, 71, 71))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(Encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCrearNuevaCuenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblContrasenia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblIniciaSesion)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        // TODO add your handling code here:        
        String nombre = txtNombre.getText();
        String email = txtEmail.getText();
        String contrasenia = new String(txtContrasenia.getPassword());

    if (email.isEmpty() || contrasenia.isEmpty() || nombre.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    if (!Validador.esEmailValido(email)) {
        JOptionPane.showMessageDialog(this, "El formato del Email es incorrecto", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    if (!Validador.esClaveValida(contrasenia)) {
        JOptionPane.showMessageDialog(this, "La contraseña debe tener al menos 8 caracteres, incluyendo una letra mayúscula, una letra minúscula, un número y un carácter especial", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    boolean nuevoUsuario = usuarioController.registrarUsuario(nombre, email, contrasenia);

    if(nuevoUsuario){        
        JOptionPane.showMessageDialog(this, "¡Registro exitoso!", "Éxito", JOptionPane.INFORMATION_MESSAGE);     
        this.dispose(); 

        LoginFrame login = new LoginFrame();
        login.setVisible(true);
        login.setLocationRelativeTo(null); 
    }
    
    else {
        JOptionPane.showMessageDialog(this, "No se pudo registrar. El email ya está en uso.", "Error", JOptionPane.ERROR_MESSAGE);

    }     
      
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void btnRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarseMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnRegistrarseMouseClicked

    private void lblIniciaSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIniciaSesionMouseClicked
        // TODO add your handling code here:
        this.dispose(); 

        LoginFrame login = new LoginFrame();
        login.setVisible(true);
        login.setLocationRelativeTo(null);            
        
    }//GEN-LAST:event_lblIniciaSesionMouseClicked

    private void lblIniciaSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIniciaSesionMouseEntered
        // TODO add your handling code here:
        
        lblIniciaSesion.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
    }//GEN-LAST:event_lblIniciaSesionMouseEntered

    private void btnRegistrarseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarseMouseEntered
        // TODO add your handling code here:
        btnRegistrarse.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnRegistrarseMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroFrame().setVisible(true);
            }
        });
    }
    
    private UsuarioController usuarioController;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Encabezado;
    private javax.swing.JLabel InterManager;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblContrasenia;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblIniciaSesion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JLabel txtCrearNuevaCuenta;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
