/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.ReporteController;
import java.awt.BorderLayout;
import java.awt.Cursor;
import javax.swing.JPanel;
import utilidades.SesionUsuario;

/**
 *
 * @author felip
 */
public class ReportePanel extends javax.swing.JPanel {
    
    

    /**
     * Creates new form MenuPrincipal
     */
    public ReportePanel() {
        initComponents();   
        initContent();
        
        
    }
    
    private void initContent(){
        
        ShowJPanel(new ReporteDatosGeneralesPanel());
    }
    
    public static void ShowJPanel(JPanel p) {
        p.setSize(780, 386);
        p.setLocation(0,0);
        
        panelDisplay.removeAll();
        panelDisplay.add(p, BorderLayout.CENTER);
        panelDisplay.revalidate();
        panelDisplay.repaint();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblTipoDeReporte = new javax.swing.JLabel();
        cmbTipoDeReporte = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        panelDisplay = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(770, 480));

        lblTitulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTitulo.setText("Reportes");

        lblTipoDeReporte.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblTipoDeReporte.setForeground(new java.awt.Color(0, 0, 0));
        lblTipoDeReporte.setText("Seleccionar tipo de reporte:");

        cmbTipoDeReporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Datos Generales", "Transacciones", "Productos", "Proveedores", "Clientes" }));
        cmbTipoDeReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbTipoDeReporteMouseEntered(evt);
            }
        });
        cmbTipoDeReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoDeReporteActionPerformed(evt);
            }
        });
        cmbTipoDeReporte.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbTipoDeReportePropertyChange(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 103, 205));

        panelDisplay.setPreferredSize(new java.awt.Dimension(770, 480));

        javax.swing.GroupLayout panelDisplayLayout = new javax.swing.GroupLayout(panelDisplay);
        panelDisplay.setLayout(panelDisplayLayout);
        panelDisplayLayout.setHorizontalGroup(
            panelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        panelDisplayLayout.setVerticalGroup(
            panelDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTipoDeReporte)
                        .addGap(18, 18, 18)
                        .addComponent(cmbTipoDeReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTitulo)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbTipoDeReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoDeReporte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(394, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 94, Short.MAX_VALUE)
                    .addComponent(panelDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoDeReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoDeReporteActionPerformed
        // TODO add your handling code here:
        String seleccion = (String) cmbTipoDeReporte.getSelectedItem();

                if (seleccion.equals("Datos Generales")) {
                    ShowJPanel(new ReporteDatosGeneralesPanel());
                    
                } else if (seleccion.equals("Productos")) {
                    ShowJPanel(new ReporteProductosPanel());
                    
                } else if (seleccion.equals("Proveedores")) {
                    ShowJPanel(new ReporteProveedoresPanel());
                    
                } else if (seleccion.equals("Clientes")) {                    
                    ShowJPanel(new ReporteClientesPanel());
                    
                } else if (seleccion.equals("Transacciones")) {
                    ShowJPanel(new ReporteTransaccionesPanel());
                }
    }//GEN-LAST:event_cmbTipoDeReporteActionPerformed

    private void cmbTipoDeReportePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbTipoDeReportePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoDeReportePropertyChange

    private void cmbTipoDeReporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbTipoDeReporteMouseEntered
        // TODO add your handling code here:
        cmbTipoDeReporte.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_cmbTipoDeReporteMouseEntered

    
    private ReporteController reporte = new ReporteController();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbTipoDeReporte;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTipoDeReporte;
    private javax.swing.JLabel lblTitulo;
    private static javax.swing.JPanel panelDisplay;
    // End of variables declaration//GEN-END:variables
}
