/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.ClienteController;
import controlador.ProductoController;
import controlador.ProveedorController;
import controlador.ReporteController;
import controlador.TransaccionController;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import modelo.Cliente;
import modelo.Producto;
import modelo.Proveedor;
import modelo.Transaccion;
import utilidades.ExportarCSV;
import utilidades.SesionUsuario;


/**
 *
 * @author felip
 */

public class ReporteProductosPanel extends javax.swing.JPanel {
    
    ProductoController productoController = new ProductoController();

    /**
     * Creates new form MenuPrincipal
     */
    
    public ReporteProductosPanel() {
        initComponents();    
        tableProductosSetStyle();
        cargarProductos();
        ordenarTabla();
               
    }
    
    private void tableProductosSetStyle(){
    JTableHeader header = tableReportesProductos.getTableHeader();
    header.setBackground(new Color(0,103,205)); 
    header.setForeground(Color.WHITE); 
    //header.setFont(new Font("Segoe UI", Font.BOLD, 14)); 
    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
    centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
    tableReportesProductos.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
    tableReportesProductos.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
    tableReportesProductos.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
    lblLoSabias.setToolTipText("Haciendo clic en el encabezado de una columna puedes ordenar los datos.");
    
    }
    
    public void ordenarTabla(){
    TableRowSorter<TableModel> sorter = new TableRowSorter<>(tableReportesProductos.getModel());
    tableReportesProductos.setRowSorter(sorter);               
    
    }
    
    private void cargarProductos() {    
        /*double ingresosTotales = productoController.obtenerIngresosTotales(1, SesionUsuario.getUsuario().getId());
        System.out.println(ingresosTotales);
        
        double montoVentas = productoController.sumarMontoTransacciones(1, SesionUsuario.getUsuario().getId());
        System.out.println(montoVentas);
        
        int itemCantidadTransacciones = productoController.contarTransacciones(1, SesionUsuario.getUsuario().getId());
        System.out.println(itemCantidadTransacciones);*/
        
        DefaultTableModel model = (DefaultTableModel) tableReportesProductos.getModel();
        model.setRowCount(0);

    int usuarioId = SesionUsuario.getUsuario().getId();

    List<Producto> productos = new ProductoController().listarPorUsuario(usuarioId);
    TransaccionController transaccionController = new TransaccionController();

    for (Producto p : productos) {
      
        double ingresosTotales = Math.round(productoController.obtenerIngresosTotales(p.getId(), usuarioId));
        double montoVentas = Math.round(productoController.sumarMontoTransacciones(p.getId(), usuarioId));
        int cantidadTransacciones = productoController.contarTransacciones(p.getId(), usuarioId);
        
        if(productoController.contarTransacciones(p.getId(), usuarioId)>0){
        model.addRow(new Object[] {
            p.getNombre(),
            cantidadTransacciones,
            montoVentas,
            ingresosTotales
                
        });
        }
    }}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReportesProductos = new javax.swing.JTable();
        lblLoSabias = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();
        btnGraficos = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(770, 480));

        lblTitulo2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTitulo2.setText("Productos");

        tableReportesProductos.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tableReportesProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cantidad de Transacciones", "Monto Total en Compra-Venta", "Ingresos por Comisiones"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableReportesProductos.getTableHeader().setReorderingAllowed(false);
        tableReportesProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tableReportesProductosMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableReportesProductosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableReportesProductos);

        lblLoSabias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lampara.png"))); // NOI18N
        lblLoSabias.setText("¿Lo sabías? ");
        lblLoSabias.setIconTextGap(0);

        btnImprimir.setBackground(new java.awt.Color(18, 90, 173));
        btnImprimir.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        btnImprimir.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimir.setText("Exportar a CSV");
        btnImprimir.setActionCommand("");
        btnImprimir.setBorderPainted(false);
        btnImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnImprimir.setFocusable(false);
        btnImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnImprimirMouseEntered(evt);
            }
        });
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnGraficos.setBackground(new java.awt.Color(18, 90, 173));
        btnGraficos.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        btnGraficos.setForeground(new java.awt.Color(255, 255, 255));
        btnGraficos.setText("Gráficos");
        btnGraficos.setActionCommand("");
        btnGraficos.setBorderPainted(false);
        btnGraficos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGraficos.setFocusable(false);
        btnGraficos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGraficosMouseEntered(evt);
            }
        });
        btnGraficos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLoSabias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGraficos, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnImprimir)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitulo2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblLoSabias)
                        .addComponent(btnGraficos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableReportesProductosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableReportesProductosMouseEntered
        // TODO add your handling code here:        
        JTableHeader header = tableReportesProductos.getTableHeader();

        int col = header.columnAtPoint(evt.getPoint());
        if (col != -1) {            
            header.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            
        } else {            
            header.setCursor(Cursor.getDefaultCursor());
            
        }

    }//GEN-LAST:event_tableReportesProductosMouseEntered

    private void tableReportesProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableReportesProductosMousePressed

    }//GEN-LAST:event_tableReportesProductosMousePressed

    private void btnImprimirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimirMouseEntered
        // TODO add your handling code here:
        btnImprimir.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnImprimirMouseEntered

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar como");
        fileChooser.setSelectedFile(new File("reporteProductos.csv"));

        int userSelection = fileChooser.showSaveDialog(this);
        
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            ExportarCSV.exportarTablaCSV(tableReportesProductos, archivo);
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnGraficosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGraficosMouseEntered
        // TODO add your handling code here:
        btnGraficos.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnGraficosMouseEntered

    private void btnGraficosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficosActionPerformed
        // TODO add your handling code here:
        
        JPopupMenu menuConfiguracion = new JPopupMenu();

        JMenuItem itemCantidadTransacciones = new JMenuItem("Cantidad de Transacciones");
        JMenuItem itemMontoTotal = new JMenuItem("Monto Total en Compra-Venta");        
        JMenuItem itemIngresos = new JMenuItem("Ingresos por Comisiones");

        menuConfiguracion.add(itemCantidadTransacciones);
        menuConfiguracion.add(itemMontoTotal);
        menuConfiguracion.add(itemIngresos);
        menuConfiguracion.show(btnGraficos, btnGraficos.getWidth(), btnGraficos.getHeight());
        
        int usuarioId = SesionUsuario.getUsuario().getId();        
        List<Producto> productos = productoController.listarPorUsuario(usuarioId);   
        
        itemCantidadTransacciones.addActionListener(e -> {
            
        GraficoTortaTransaccionesPanel panelTorta = new GraficoTortaTransaccionesPanel(productos, productoController, usuarioId);
        panelTorta.setPreferredSize(new Dimension(500, 350));

        JFrame frame = new JFrame("InterManager - Transacciones por Producto");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.getContentPane().add(panelTorta);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
            
        });
        
        itemMontoTotal.addActionListener(e -> {
            
        GraficoTortaMontosPanel panelTorta = new GraficoTortaMontosPanel(productos, productoController, usuarioId);
        panelTorta.setPreferredSize(new Dimension(500, 350));

        JFrame frame = new JFrame("InterManager - Volumen total en Transacciones por Producto");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.getContentPane().add(panelTorta);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
            
        });
        
        itemIngresos.addActionListener(e -> {
            
        GraficoTortaIngresosTotalesPanel panelTorta = new GraficoTortaIngresosTotalesPanel(productos, productoController, usuarioId);
        panelTorta.setPreferredSize(new Dimension(500, 350));

        JFrame frame = new JFrame("InterManager - Ingresos Totales por Producto");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.getContentPane().add(panelTorta);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
            
        });

        
    }//GEN-LAST:event_btnGraficosActionPerformed

    
    private ReporteController reporte = new ReporteController();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGraficos;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLoSabias;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JTable tableReportesProductos;
    // End of variables declaration//GEN-END:variables
}
