/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.ProveedorController;
import controlador.ReporteController;
import controlador.TransaccionController;
import java.awt.Color;
import java.awt.Cursor;
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import modelo.Proveedor;
import modelo.Transaccion;
import utilidades.ExportarCSV;
import utilidades.SesionUsuario;

/**
 *
 * @author felip
 */
public class ReporteTransaccionesPanel extends javax.swing.JPanel {
    
    TransaccionController transaccionController = new TransaccionController();

    /**
     * Creates new form MenuPrincipal
     */
    public ReporteTransaccionesPanel() {
        initComponents();    
        tableReportesTransaccionesSetStyle();
        cargarTransacciones();
        ordenarTabla();
               
    }
    
    private void tableReportesTransaccionesSetStyle(){
    JTableHeader header = tableReportesTransacciones.getTableHeader();
    header.setBackground(new Color(0,103,205)); // Color de fondo (azul por ejemplo)
    header.setForeground(Color.WHITE); // Color del texto
    //header.setFont(new Font("Segoe UI", Font.BOLD, 14)); // Fuente
    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
    centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
    tableReportesTransacciones.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
    tableReportesTransacciones.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
    tableReportesTransacciones.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
    lblLoSabias.setToolTipText("Haciendo clic en el encabezado de una columna puedes ordenar los datos.");
    
    }
    
    public void ordenarTabla(){
    TableRowSorter<TableModel> sorter = new TableRowSorter<>(tableReportesTransacciones.getModel());
    tableReportesTransacciones.setRowSorter(sorter);   
    
    }
    
    private void cargarTransacciones() {    
        
        DefaultTableModel model = (DefaultTableModel) tableReportesTransacciones.getModel();
        model.setRowCount(0);

     int usuarioId = SesionUsuario.getUsuario().getId();

     List<Transaccion> transacciones = new TransaccionController().listarPorUsuario(usuarioId);
     TransaccionController transaccionController = new TransaccionController();

     for (Transaccion t : transacciones) {      
        double comisionTotalPorcentaje = this.transaccionController.comisionTotalPorcentaje(t);
        double comisionTotalNeta = this.transaccionController.comisionTotalNeta(t);      
        
        model.addRow(new Object[] {
            t.getNombreProveedor(),
            t.getNombreCliente(),
            t.getNombreProducto(),
            t.getMonto(),            
            comisionTotalPorcentaje,
            comisionTotalNeta
        });
        
     }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReportesTransacciones = new javax.swing.JTable();
        lblLoSabias = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(770, 480));

        lblTitulo2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTitulo2.setText("Transacciones");

        tableReportesTransacciones.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tableReportesTransacciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Proveedor", "Cliente", "Producto", "Monto", "Comision Total %", "Comision Total Neta"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableReportesTransacciones.getTableHeader().setReorderingAllowed(false);
        tableReportesTransacciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tableReportesTransaccionesMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableReportesTransaccionesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableReportesTransacciones);

        lblLoSabias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lampara.png"))); // NOI18N
        lblLoSabias.setText("¿Lo sabías? ");
        lblLoSabias.setIconTextGap(0);

        btnImprimir.setBackground(new java.awt.Color(18, 90, 173));
        btnImprimir.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        btnImprimir.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimir.setText("Exportar a CSV");
        btnImprimir.setActionCommand("");
        btnImprimir.setBorderPainted(false);
        btnImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnImprimir.setFocusable(false);
        btnImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnImprimirMouseEntered(evt);
            }
        });
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLoSabias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnImprimir)
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblLoSabias)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableReportesTransaccionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableReportesTransaccionesMouseEntered
        // TODO add your handling code here:        
        JTableHeader header = tableReportesTransacciones.getTableHeader();
        int col = header.columnAtPoint(evt.getPoint());
        if (col != -1) {
            // Cambiar a la manito
            header.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        } else {
            // Volver al cursor por defecto
            header.setCursor(Cursor.getDefaultCursor());
        }

    }//GEN-LAST:event_tableReportesTransaccionesMouseEntered

    private void tableReportesTransaccionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableReportesTransaccionesMousePressed
       
    }//GEN-LAST:event_tableReportesTransaccionesMousePressed

    private void btnImprimirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimirMouseEntered
        // TODO add your handling code here:
        btnImprimir.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnImprimirMouseEntered
    
    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar como");
        fileChooser.setSelectedFile(new File("reporteTransacciones.csv"));
        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            ExportarCSV.exportarTablaCSV(tableReportesTransacciones, archivo);
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    
    private ReporteController reporte = new ReporteController();
        
        
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLoSabias;
    private javax.swing.JLabel lblTitulo2;
    private javax.swing.JTable tableReportesTransacciones;
    // End of variables declaration//GEN-END:variables
}
