/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.ReporteController;
import controlador.TransaccionController;
import java.awt.Color;
import java.time.LocalDate;
import java.util.Map;
import utilidades.SesionUsuario;

/**
 *
 * @author felip
 */
public class ReporteDatosGeneralesPanel extends javax.swing.JPanel {
    
    

    /**
     * Creates new form MenuPrincipal
     */
    public ReporteDatosGeneralesPanel() {
        initComponents();    
        setText();
        
    }
    
    public void setText(){
    lblReporte1.setText("Cantidad de Transacciones: " + reporte.cantidadTransacciones(SesionUsuario.getUsuario().getId()));    
    lblReporte2.setText("Ingresos Totales: " + (int)reporte.ingresosTotales(SesionUsuario.getUsuario().getId()) + "$");
    lblReporte3.setText("Ingresos por Proveedores: " + (int)reporte.ingresosPorProveedores(SesionUsuario.getUsuario().getId()) + "$");   
    lblReporte4.setText("Ingresos por Clientes: " + (int)reporte.ingresosPorClientes(SesionUsuario.getUsuario().getId()) + "$");
    
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo2 = new javax.swing.JLabel();
        lblReporte4 = new javax.swing.JLabel();
        lblReporte3 = new javax.swing.JLabel();
        lblReporte1 = new javax.swing.JLabel();
        lblReporte2 = new javax.swing.JLabel();
        jPanel1 = new vista.GraficoIngresosFechasPanel(ingresosMap);

        setPreferredSize(new java.awt.Dimension(770, 480));

        lblTitulo2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTitulo2.setText("Datos Generales");

        lblReporte4.setBackground(new java.awt.Color(0, 103, 205));
        lblReporte4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblReporte4.setForeground(new java.awt.Color(255, 255, 255));
        lblReporte4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblReporte4.setText("reporte 4");
        lblReporte4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        lblReporte4.setOpaque(true);

        lblReporte3.setBackground(new java.awt.Color(0, 103, 205));
        lblReporte3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblReporte3.setForeground(new java.awt.Color(255, 255, 255));
        lblReporte3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblReporte3.setText("reporte 3");
        lblReporte3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        lblReporte3.setOpaque(true);

        lblReporte1.setBackground(new java.awt.Color(0, 103, 205));
        lblReporte1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblReporte1.setForeground(new java.awt.Color(255, 255, 255));
        lblReporte1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblReporte1.setText("reporte 1");
        lblReporte1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        lblReporte1.setOpaque(true);

        lblReporte2.setBackground(new java.awt.Color(0, 103, 205));
        lblReporte2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblReporte2.setForeground(new java.awt.Color(255, 255, 255));
        lblReporte2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblReporte2.setText("reporte 2");
        lblReporte2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        lblReporte2.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitulo2)
                    .addComponent(lblReporte4, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addComponent(lblReporte3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblReporte2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblReporte1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitulo2)
                        .addGap(26, 26, 26)
                        .addComponent(lblReporte1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblReporte2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblReporte3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblReporte4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 182, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private ReporteController reporte = new ReporteController();
    Map<LocalDate, Double> ingresosMap = new TransaccionController().ingresosUltimos30Dias(SesionUsuario.getUsuario().getId());
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblReporte1;
    private javax.swing.JLabel lblReporte2;
    private javax.swing.JLabel lblReporte3;
    private javax.swing.JLabel lblReporte4;
    private javax.swing.JLabel lblTitulo2;
    // End of variables declaration//GEN-END:variables
}
