/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.ClienteController;
import controlador.MetodoPagoController;
import controlador.ProductoController;
import controlador.ProveedorController;
import controlador.TransaccionController;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.GridLayout;
import java.io.File;
import java.time.LocalDate;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import modelo.Cliente;
import modelo.MetodoPago;
import modelo.Producto;
import modelo.Proveedor;
import modelo.Transaccion;
import utilidades.ExportarCSV;
import utilidades.SesionUsuario;

/**
 *
 * @author felip
 */
public class TransaccionPanel extends javax.swing.JPanel {

    private TransaccionController controller = new TransaccionController();

    public TransaccionPanel() {
    initComponents();
    cargarTransacciones("");
    tableTransaccionesSetStyle();
    ordenarTabla();
    }
    
    private void tableTransaccionesSetStyle(){
    JTableHeader header = tableTransacciones.getTableHeader();
    header.setBackground(new Color(0,103,205)); 
    header.setForeground(Color.WHITE); 
    //header.setFont(new Font("Segoe UI", Font.BOLD, 14)); 
    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
    centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
    
    tableTransacciones.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
    tableTransacciones.getColumnModel().getColumn(5).setCellRenderer(centerRenderer);
    tableTransacciones.getColumnModel().getColumn(6).setCellRenderer(centerRenderer);
    tableTransacciones.getColumnModel().getColumn(7).setCellRenderer(centerRenderer);
    lblLoSabias.setToolTipText("Haciendo clic en el encabezado de una columna puedes ordenar los datos.");
    }
    
    private void cargarTransacciones(String filtro) {
    
        DefaultTableModel model = (DefaultTableModel) tableTransacciones.getModel();
        model.setRowCount(0);

        List<Transaccion> lista = controller.listarPorUsuario(SesionUsuario.getUsuario().getId());

        for (Transaccion t : lista) {
            String proveedor = t.getNombreProveedor();
            String cliente = t.getNombreCliente();
            String producto = t.getNombreProducto();
            String metodoPago = t.getNombreMetodoPago();

            // si el filtro está vacío o coincide con proveedor, cliente o producto.
            if (filtro.isEmpty() ||
                proveedor.toLowerCase().contains(filtro.toLowerCase()) ||
                cliente.toLowerCase().contains(filtro.toLowerCase()) ||
                producto.toLowerCase().contains(filtro.toLowerCase())) {

                model.addRow(new Object[]{
                t.getId(),
                t.getFecha().toString(),
                producto,
                proveedor,
                cliente,
                t.getMonto(),
                t.getPorcentajeProveedor(),
                t.getPorcentajeCliente(),
                metodoPago
            });
        }
    }
        
}
    
    public void ordenarTabla(){
        
    TableRowSorter<TableModel> sorter = new TableRowSorter<>(tableTransacciones.getModel());
    tableTransacciones.setRowSorter(sorter);    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userSearch = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransacciones = new javax.swing.JTable();
        txtfieldBuscador = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblTitulo1 = new javax.swing.JLabel();
        lblLoSabias = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(770, 480));

        lblTitulo.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblTitulo.setText("Gestión de Transacciones");

        tableTransacciones.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tableTransacciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "Producto", "Proveedor", "Cliente", "Monto", "% Proveedor", "% Cliente", "Tipo de Pago"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableTransacciones.getTableHeader().setReorderingAllowed(false);
        tableTransacciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tableTransaccionesMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableTransaccionesMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableTransacciones);

        btnBuscar.setBackground(new java.awt.Color(18, 90, 173));
        btnBuscar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setBorderPainted(false);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuscar.setFocusable(false);
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
        });
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnNuevo.setBackground(new java.awt.Color(18, 90, 173));
        btnNuevo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorderPainted(false);
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNuevo.setFocusable(false);
        btnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNuevoMouseEntered(evt);
            }
        });
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(18, 90, 173));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.setBorderPainted(false);
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditar.setFocusable(false);
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarMouseEntered(evt);
            }
        });
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(18, 90, 173));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Borrar");
        btnEliminar.setBorderPainted(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminar.setFocusable(false);
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblTitulo1.setForeground(new java.awt.Color(126, 126, 126));
        lblTitulo1.setText("Filtrar por Producto, Proveedor o Cliente");

        lblLoSabias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lampara.png"))); // NOI18N
        lblLoSabias.setText("¿Lo sabías? ");
        lblLoSabias.setIconTextGap(0);

        btnImprimir.setBackground(new java.awt.Color(18, 90, 173));
        btnImprimir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnImprimir.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimir.setText("Exportar a CSV");
        btnImprimir.setActionCommand("");
        btnImprimir.setBorderPainted(false);
        btnImprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnImprimir.setFocusable(false);
        btnImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnImprimirMouseEntered(evt);
            }
        });
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblLoSabias)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtfieldBuscador)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE))
                    .addComponent(lblTitulo1))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfieldBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminar)
                            .addComponent(btnEditar)
                            .addComponent(btnNuevo)
                            .addComponent(btnImprimir)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblLoSabias)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tableTransaccionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTransaccionesMousePressed

    }//GEN-LAST:event_tableTransaccionesMousePressed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        cargarTransacciones(txtfieldBuscador.getText().trim());
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        
    List<Proveedor> proveedores = new ProveedorController().listarPorUsuario(SesionUsuario.getUsuario().getId())    
    .stream()
    .filter(p -> p.isActivo())
    .collect(Collectors.toList());
    List<Cliente> clientes = new ClienteController().listarPorUsuario(SesionUsuario.getUsuario().getId())
    .stream()
    .filter(p -> p.isActivo())
    .collect(Collectors.toList());
    List<Producto> productos = new ProductoController().listarPorUsuario(SesionUsuario.getUsuario().getId())
    .stream()
    .filter(p -> p.isActivo())
    .collect(Collectors.toList());
    List<MetodoPago> metodosPago = new MetodoPagoController().listar();

    JComboBox<Proveedor> cbProveedor = new JComboBox<>(proveedores.toArray(new Proveedor[0]));
    JComboBox<Cliente> cbCliente = new JComboBox<>(clientes.toArray(new Cliente[0]));
    JComboBox<Producto> cbProducto = new JComboBox<>(productos.toArray(new Producto[0]));
    JComboBox<MetodoPago> cbMetodo = new JComboBox<>(metodosPago.toArray(new MetodoPago[0]));

    JTextField fieldFecha = new JTextField(LocalDate.now().toString());
    JTextField fieldMonto = new JTextField();
    JTextField fieldPorcProv = new JTextField();
    JTextField fieldPorcCli = new JTextField();

    JPanel panel = new JPanel(new GridLayout(0, 1));
    panel.add(new JLabel("Proveedor:"));
    panel.add(cbProveedor);
    panel.add(new JLabel("Cliente:"));
    panel.add(cbCliente);
    panel.add(new JLabel("Producto:"));
    panel.add(cbProducto);
    panel.add(new JLabel("Método de pago:"));
    panel.add(cbMetodo);
    panel.add(new JLabel("Fecha (yyyy-MM-dd):"));
    panel.add(fieldFecha);
    panel.add(new JLabel("Monto:"));
    panel.add(fieldMonto);
    panel.add(new JLabel("% Proveedor:"));
    panel.add(fieldPorcProv);
    panel.add(new JLabel("% Cliente:"));
    panel.add(fieldPorcCli);

    int result = JOptionPane.showConfirmDialog(this, panel, "Nueva Transacción", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

    if (result == JOptionPane.OK_OPTION) {
        
        try {
            Transaccion t = new Transaccion();
            t.setProveedorId(((Proveedor) cbProveedor.getSelectedItem()).getId());
            t.setClienteId(((Cliente) cbCliente.getSelectedItem()).getId());
            t.setProductoId(((Producto) cbProducto.getSelectedItem()).getId());
            t.setMetodoPagoId(((MetodoPago) cbMetodo.getSelectedItem()).getId());
            t.setFecha(LocalDate.parse(fieldFecha.getText().trim()));
            t.setMonto(Double.parseDouble(fieldMonto.getText().trim()));
            t.setPorcentajeProveedor(Double.parseDouble(fieldPorcProv.getText().trim()));
            t.setPorcentajeCliente(Double.parseDouble(fieldPorcCli.getText().trim()));
            t.setUsuarioId(SesionUsuario.getUsuario().getId());

            //boolean exito = controller.crearTransaccion(t);
            
            boolean exito = controller.crearTransaccion(
                t.getFecha(),
                t.getProveedorId(),
                t   .getClienteId(),
                t.getMetodoPagoId(),
                t.getProductoId(),
                t.getMonto(),
                t.getPorcentajeProveedor(),
                t.getPorcentajeCliente(),
                t.getUsuarioId()
);
            if (exito) {
                cargarTransacciones("");
                
            } else {
                JOptionPane.showMessageDialog(this, "Error al crear la transacción.");
                
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Datos inválidos. Intenta nuevamente");
            
       }
   }
        
    }//GEN-LAST:event_btnNuevoActionPerformed
   
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       
        int fila = tableTransacciones.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona una transacción para editar.");
        return;
    }

    int id = (int) tableTransacciones.getValueAt(fila, 0);
    String fechaActual = tableTransacciones.getValueAt(fila, 1).toString();
    String productoActual = tableTransacciones.getValueAt(fila, 2).toString();
    String proveedorActual = tableTransacciones.getValueAt(fila, 3).toString();
    String clienteActual = tableTransacciones.getValueAt(fila, 4).toString();
    String montoActual = tableTransacciones.getValueAt(fila, 5).toString();
    String porcentajeProvActual = tableTransacciones.getValueAt(fila, 6).toString();
    String porcentajeCliActual = tableTransacciones.getValueAt(fila, 7).toString();
    String metodoPagoActual = tableTransacciones.getValueAt(fila, 8).toString();

    try {
        List<Producto> productos = new ProductoController().listarPorUsuario(SesionUsuario.getUsuario().getId());
        List<Proveedor> proveedores = new ProveedorController().listarPorUsuario(SesionUsuario.getUsuario().getId())
                .stream().filter(p -> p.isActivo()).collect(Collectors.toList());
        List<Cliente> clientes = new ClienteController().listarPorUsuario(SesionUsuario.getUsuario().getId())
                .stream().filter(c -> c.isActivo()).collect(Collectors.toList());
        List<MetodoPago> metodosPago = new MetodoPagoController().listar();

        JPanel panel = new JPanel(new GridLayout(8, 2, 10, 10));

        JTextField txtFecha = new JTextField(fechaActual);
        JComboBox<Producto> cbProducto = new JComboBox<>(productos.toArray(new Producto[0]));
        JComboBox<Proveedor> cbProveedor = new JComboBox<>(proveedores.toArray(new Proveedor[0]));
        JComboBox<Cliente> cbCliente = new JComboBox<>(clientes.toArray(new Cliente[0]));
        JComboBox<MetodoPago> cbMetodoPago = new JComboBox<>(metodosPago.toArray(new MetodoPago[0]));
        JTextField txtMonto = new JTextField(montoActual);
        JTextField txtPorcentajeProv = new JTextField(porcentajeProvActual);
        JTextField txtPorcentajeCli = new JTextField(porcentajeCliActual);

        
        cbProducto.setSelectedItem(productos.stream().filter(p -> p.toString().equals(productoActual)).findFirst().orElse(null));
        cbProveedor.setSelectedItem(proveedores.stream().filter(p -> p.toString().equals(proveedorActual)).findFirst().orElse(null));
        cbCliente.setSelectedItem(clientes.stream().filter(c -> c.toString().equals(clienteActual)).findFirst().orElse(null));
        cbMetodoPago.setSelectedItem(metodosPago.stream().filter(m -> m.toString().equals(metodoPagoActual)).findFirst().orElse(null));

        panel.add(new JLabel("Fecha (yyyy-MM-dd):"));
        panel.add(txtFecha);
        panel.add(new JLabel("Producto:"));
        panel.add(cbProducto);
        panel.add(new JLabel("Proveedor:"));
        panel.add(cbProveedor);
        panel.add(new JLabel("Cliente:"));
        panel.add(cbCliente);
        panel.add(new JLabel("Método de Pago:"));
        panel.add(cbMetodoPago);
        panel.add(new JLabel("Monto:"));
        panel.add(txtMonto);
        panel.add(new JLabel("% Proveedor:"));
        panel.add(txtPorcentajeProv);
        panel.add(new JLabel("% Cliente:"));
        panel.add(txtPorcentajeCli);

        int result = JOptionPane.showConfirmDialog(null, panel, "Editar Transacción", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            
            LocalDate fecha = LocalDate.parse(txtFecha.getText().trim());
            double monto = Double.parseDouble(txtMonto.getText().trim());
            double porcentajeProv = Double.parseDouble(txtPorcentajeProv.getText().trim());
            double porcentajeCli = Double.parseDouble(txtPorcentajeCli.getText().trim());

            Producto productoSel = (Producto) cbProducto.getSelectedItem();
            Proveedor proveedorSel = (Proveedor) cbProveedor.getSelectedItem();
            Cliente clienteSel = (Cliente) cbCliente.getSelectedItem();
            MetodoPago metodoPagoSel = (MetodoPago) cbMetodoPago.getSelectedItem();

            boolean exito = controller.actualizar(id, fecha, proveedorSel.getId(), clienteSel.getId(),
                    metodoPagoSel.getId(), productoSel.getId(), monto, porcentajeProv,
                    porcentajeCli, SesionUsuario.getUsuario().getId());

            if (exito) {
                cargarTransacciones("");
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar la transacción.");
            }
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Datos inválidos. Intenta nuevamente.");
        e.printStackTrace();
    }
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
        int fila = tableTransacciones.getSelectedRow();
        if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona una transacción para eliminar.");
        return;
        }

        int id = (int) tableTransacciones.getValueAt(fila, 0);
        int confirm = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas eliminar esta transacción?");
        
        if (confirm == JOptionPane.YES_OPTION) {
            boolean exito = controller.eliminar(id, SesionUsuario.getUsuario().getId());
            if (exito) {
                cargarTransacciones("");
        } else {
            JOptionPane.showMessageDialog(this, "No se puede eliminar.");
        }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tableTransaccionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTransaccionesMouseEntered
        // TODO add your handling code here:
        
        JTableHeader header = tableTransacciones.getTableHeader();
        
        int col = header.columnAtPoint(evt.getPoint());
        if (col != -1) {           
            header.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            
        } else {            
            header.setCursor(Cursor.getDefaultCursor());
            
        }
        
    }//GEN-LAST:event_tableTransaccionesMouseEntered

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        // TODO add your handling code here:
        btnBuscar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnNuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseEntered
        // TODO add your handling code here:
        btnNuevo.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnNuevoMouseEntered

    private void btnEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseEntered
        // TODO add your handling code here:
        btnEditar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnEditarMouseEntered

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        // TODO add your handling code here:
        btnEliminar.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnImprimirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimirMouseEntered
        // TODO add your handling code here:
        btnImprimir.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnImprimirMouseEntered

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar como");
        fileChooser.setSelectedFile(new File("transacciones.csv"));

        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            ExportarCSV.exportarTablaCSV(tableTransacciones, archivo);
        }
        
        
    }//GEN-LAST:event_btnImprimirActionPerformed

 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLoSabias;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JTable tableTransacciones;
    private javax.swing.JTextField txtfieldBuscador;
    private javax.swing.JTextField userSearch;
    // End of variables declaration//GEN-END:variables
}
